### ISSUE TITLE
FAAV Profiles API 403 Error

### ISSUE THREAD

**Issue by mciolkosz** [withdrew/Unofficial-NameMC-API-Docs#3]
Just want to start this off: If I'm missing the correct repository, please let me know, and I'll reopen this issue in the correct location. I'm opening it here because the repo recommends using the API.

The Profiles API will give me the occational 403 error when running it via automation vs. via a wget command. I'm only polling the API every 5 seconds (give or take a few millis), so I'm not trying to rate limit myself. I've taken a look at the [docs here](https://faav.gapple.pw/profiles/), but I'm not sure about the 403 errors.

A PasteBin link for the error can be found [here](https://pastebin.com/xRPehRG1).
A PasteBin link for the code (Java) that's calling the API can be found [here](https://pastebin.com/uyKC4456). (The same general code is used to call the official Mojang API, with no issues, so I'm fairly certain it's not the code itself).

If there are any docs that I'm missing, or additonal information that's needed, please let me know.

**Comment by bribes** [comment]
Is there any reason why you are using this endpoint specifically? You can try using api.gapple.pw instead as it has similar routes.

**Comment by mciolkosz** [comment]
api.gapple.pw doesn't have the profiles/ endpoint that faav.gapple.pw has, so I can't look up the (potentially multiple) profiles that have had the name "example", for example.

I guess I didn't make it super clear in the original post, I'm looking to use the faav api as it will allow me to look up if there has been any use of a specific name by 1 or more accounts, vs the other API that only appears to perform lookups based on current name.

**Comment by bribes** [comment]
Well I can't really help the ratelimits are based off laby.net.

**Comment by mciolkosz** [comment]
Ok, thank you. Do you know what the rate limits are, or where the documentation for that is?

**Comment by mciolkosz** [comment]
Found out what was wrong with the 403 error: It required a UserAgent to be set before getting the InputStream:
```
75 |         final URL url = new URL(PROFILES_URL.replace("<username>", name));
76 |         final HttpURLConnection connection = (HttpURLConnection) url.openConnection();
77 |         connection.addRequestProperty("User-Agent", "Wget/1.21"); // This needed to be added, I used the WGET UserAgent
78 |         connection.setRequestMethod("GET");
```

Hope this can help someone else in the future.
